#!/bin/sh
set -e

if [ -L /boot/boot/boot.cfg ]; then
	# Do nothing if the file is already a symlink
	exit 0
fi

mv /boot/boot/boot.cfg /boot/boot/boot.cfg.orig-before-leste
ln -s /boot/boot/boot.cfg.leste /boot/boot/boot.cfg

cat <<EOM
**********************************************
                WARNING
The kexecboot file in /boot/boot/boot.cfg was
moved to /boot/boot/boot.cfg.orig-before-leste
and the new file was symlinked. If you want
to restore your old boot.cfg, please change
this symlink to link to your old file.

If you never made changes to your existing
file, then it is safe to ignore this warning
**********************************************
EOM

exit 0
